<a href="https://colab.research.google.com/github/GaneshaNHotti/DSLAB/blob/main/ID3vCart.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!rm -rf iris.csv
!wget https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv

--2022-02-18 05:35:26--  https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv
Resolving gist.githubusercontent.com (gist.githubusercontent.com)... 185.199.109.133, 185.199.111.133, 185.199.110.133, ...
Connecting to gist.githubusercontent.com (gist.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3975 (3.9K) [text/plain]
Saving to: ‘iris.csv’

iris.csv            100%[===================>]   3.88K  --.-KB/s    in 0s

2022-02-18 05:35:26 (72.2 MB/s) - ‘iris.csv’ saved [3975/3975]

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score

In [3]:
df = pd.read_csv('/content/iris.csv')
df.head()

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [4]:
df['class'] = df['variety'].map(
    {
        'Setosa': 0,
        'Versicolor': 1,
        'Virginica': 2
    }
)

In [5]:
X = df[['sepal.length', 'sepal.width', 'petal.length', 'petal.width']]
X

     sepal.length  sepal.width  petal.length  petal.width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [6]:
Y = df[['class']]
Y

     class
0        0
1        0
2        0
3        0
4        0
..     ...
145      2
146      2
147      2
148      2
149      2

[150 rows x 1 columns]

In [7]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=1)

In [8]:
id3 = DecisionTreeClassifier(criterion='entropy')
cart = DecisionTreeClassifier(criterion='gini')

In [9]:
id3_model = id3.fit(X_train, Y_train)
cart_model = cart.fit(X_train, Y_train)
Y_id3 = id3_model.predict(X_test)
Y_cart = cart_model.predict(X_test)

In [10]:
accuracy = accuracy_score(Y_test, Y_id3)
recall = recall_score(Y_test, Y_id3, average='micro')
precision = precision_score(Y_test, Y_id3, average='micro')
f1 = f1_score(Y_test, Y_id3, average='micro')
print("Accuracy:", accuracy)
print("Error Rate:", 1.0-accuracy)
print("Recall:", recall)
print("Precision:", precision)
print("F1 Score:", f1)

Accuracy: 0.9555555555555556
Error Rate: 0.0444444444444444
Recall: 0.9555555555555556
Precision: 0.9555555555555556
F1 Score: 0.9555555555555556

In [11]:
accuracy = accuracy_score(Y_test, Y_cart)
recall = recall_score(Y_test, Y_cart, average='micro')
precision = precision_score(Y_test, Y_cart, average='micro')
f1 = f1_score(Y_test, Y_cart, average='micro')
print("Accuracy:", accuracy)
print("Error Rate:", 1.0-accuracy)
print("Recall:", recall)
print("Precision:", precision)
print("F1 Score:", f1)

Accuracy: 0.9555555555555556
Error Rate: 0.0444444444444444
Recall: 0.9555555555555556
Precision: 0.9555555555555556
F1 Score: 0.9555555555555556